### ISSUE TITLE
Make get request with where filter

### ISSUE THREAD

**Issue by TomskDiver** [Si1kIfY/google-app-script-xero-api#4]
Hello.
I try make api get request  for invoices with "where date" filter by your code.
I try write url as `https://api.xero.com/api.xro/2.0/invoices?where='+encodeURIComponent('Date==DateTime(2019,11,27)')` or `https://api.xero.com/api.xro/2.0/invoices?where=Date==DateTime(2019,11,27)`
And response be: `oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature`
Please, help.

**Comment by csi-lk** [comment]
Haven't looked at this in a few years now but as per your response saying 'Failed to validate signature' I'd say it's a problem with your token?

Maybe contact Xero support for help
